-- Create disability diagnoses lookup table if it does not exist
CREATE TABLE IF NOT EXISTS `tbl_disability_diagnoses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `disability_id` int(11) DEFAULT NULL,
  `diagnosis` varchar(255) NOT NULL,
  `status` enum('Active','Inactive') DEFAULT 'Active',
  `created_by` int(11) DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_disability_diagnoses_disability_id` (`disability_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed master data (idempotent)
INSERT INTO `tbl_disability_diagnoses` (`id`, `disability_id`, `diagnosis`, `status`, `created_by`, `created_on`, `updated_by`, `updated_on`) VALUES
(1, 1, 'Bilateral profound hearing loss', 'Active', NULL, NULL, NULL, NULL),
(2, 1, 'Bil Severe to Profound Hearing loss', 'Active', NULL, NULL, NULL, NULL),
(3, 1, 'Bilateral profound SN hearing loss', 'Active', NULL, NULL, NULL, NULL),
(4, 1, 'Rt - Severe SN Hearing loss', 'Active', NULL, NULL, NULL, NULL),
(5, 1, 'Lt- Profound Hearing loss', 'Active', NULL, NULL, NULL, NULL),
(6, 1, 'RT Profound Mixed Hearing Loss', 'Active', NULL, NULL, NULL, NULL),
(7, 1, 'LT Moderate Sens Mixed Hearing Loss', 'Active', NULL, NULL, NULL, NULL),
(8, 1, 'Bilateral Severe Hearing Loss', 'Active', NULL, NULL, NULL, NULL),
(9, 2, 'BE Microphthalmia with Nystagmus', 'Active', NULL, NULL, NULL, NULL),
(10, 2, 'RE Optic Atrophy, LE Retinal', 'Active', NULL, NULL, NULL, NULL),
(11, 2, 'BE Optic Atrophy', 'Active', NULL, NULL, NULL, NULL),
(12, 2, 'Both Eye Macular Choroiditis with Retinal Degeneration', 'Active', NULL, NULL, NULL, NULL),
(13, 2, 'Both Eye Anterior Staphyloma', 'Active', NULL, NULL, NULL, NULL),
(14, 2, 'RE Corneal Opacity, LE Phthisis Bulbi', 'Active', NULL, NULL, NULL, NULL),
(15, 2, 'BE Developmental Cataract', 'Active', NULL, NULL, NULL, NULL),
(16, 2, 'BE Retinitis Pigmentosa', 'Active', NULL, NULL, NULL, NULL),
(17, 3, 'Bil L/L Paraplegia po l1 fracture', 'Active', NULL, NULL, NULL, NULL),
(18, 3, 'PPRP Bilateral L/L', 'Active', NULL, NULL, NULL, NULL),
(19, 3, 'Multiple Exostosis with Bilateral L/L Deformity', 'Active', NULL, NULL, NULL, NULL),
(20, 3, 'Rt Hip Disarticulation', 'Active', NULL, NULL, NULL, NULL),
(21, 3, 'Spastic Diplegla', 'Active', NULL, NULL, NULL, NULL),
(22, 3, 'Spasticity Bil. L/L', 'Active', NULL, NULL, NULL, NULL),
(23, 3, 'Bil Hip Ankylosis Bil ankit ankylosis', 'Active', NULL, NULL, NULL, NULL),
(24, 3, 'Musculer Dystrophy', 'Active', NULL, NULL, NULL, NULL),
(25, 3, 'RT L/L Shortning', 'Active', NULL, NULL, NULL, NULL),
(26, 3, 'Bilateral Paraparesis', 'Active', NULL, NULL, NULL, NULL),
(27, 3, 'Paraparesis both l/l', 'Active', NULL, NULL, NULL, NULL),
(28, 3, 'CP with diplegia', 'Active', NULL, NULL, NULL, NULL),
(29, 4, 'Bil L/L Paraplegia po l1 fracture', 'Active', NULL, NULL, NULL, NULL),
(30, 4, 'PPRP Bilateral L/L', 'Active', NULL, NULL, NULL, NULL),
(31, 4, 'Multiple Exostosis with Bilateral L/L Deformity', 'Active', NULL, NULL, NULL, NULL),
(32, 4, 'Rt Hip Disarticulation', 'Active', NULL, NULL, NULL, NULL),
(33, 4, 'Spastic Diplegla', 'Active', NULL, NULL, NULL, NULL),
(34, 4, 'Spasticity Bil. L/L', 'Active', NULL, NULL, NULL, NULL),
(35, 4, 'Bil Hip Ankylosis Bil ankit ankylosis', 'Active', NULL, NULL, NULL, NULL),
(36, 4, 'Musculer Dystrophy', 'Active', NULL, NULL, NULL, NULL),
(37, 5, 'Severe Intellectual Disability', 'Active', NULL, NULL, NULL, NULL),
(38, 5, 'Profound Intellectual Disability', 'Active', NULL, NULL, NULL, NULL),
(39, 5, 'Intellectual disability Mild Mental Retardation', 'Active', NULL, NULL, NULL, NULL),
(40, 5, 'Moderate Intellectual Disability', 'Active', NULL, NULL, NULL, NULL),
(41, 5, 'Mental Retardation', 'Active', NULL, NULL, NULL, NULL),
(42, 5, 'Intellectual Disability', 'Active', NULL, NULL, NULL, NULL),
(43, 5, 'Mild Mntal Retardation', 'Active', NULL, NULL, NULL, NULL),
(44, 5, 'Mild Intellectual Disability', 'Active', NULL, NULL, NULL, NULL),
(45, 5, 'Severe Mental Retardation', 'Active', NULL, NULL, NULL, NULL),
(46, 6, 'Severe Intellectual Disability', 'Active', NULL, NULL, NULL, NULL),
(47, 6, 'Profound Intellectual Disability', 'Active', NULL, NULL, NULL, NULL),
(48, 6, 'Intellectual disability Mild Mental Retardation', 'Active', NULL, NULL, NULL, NULL),
(49, 6, 'Moderate Intellectual Disability', 'Active', NULL, NULL, NULL, NULL),
(50, 6, 'Mental Retardation', 'Active', NULL, NULL, NULL, NULL),
(51, 6, 'Intellectual Disability', 'Active', NULL, NULL, NULL, NULL),
(52, 6, 'Mild Mntal Retardation', 'Active', NULL, NULL, NULL, NULL),
(53, 6, 'Mild Intellectual Disability', 'Active', NULL, NULL, NULL, NULL),
(54, 6, 'Severe Mental Retardation', 'Active', NULL, NULL, NULL, NULL),
(55, 7, 'BE Micropthalmas with Nystagmas', 'Active', NULL, NULL, NULL, NULL),
(56, 7, 'RE Optic Atrophy LE Retinal', 'Active', NULL, NULL, NULL, NULL),
(57, 7, 'BE Optic Athophy', 'Active', NULL, NULL, NULL, NULL),
(58, 7, 'Both eye macular choridoitis with retinal degeration', 'Active', NULL, NULL, NULL, NULL),
(59, 7, 'Bothe Eye Anterior Staphylloma', 'Active', NULL, NULL, NULL, NULL),
(60, 7, 'RE Corneal Opacity LE Pthisis Bulbi', 'Active', NULL, NULL, NULL, NULL),
(61, 7, 'BE Devlopment catract', 'Active', NULL, NULL, NULL, NULL),
(62, 7, 'BE Retinitis Pigmentosa', 'Active', NULL, NULL, NULL, NULL),
(63, 1, 'Bil Moderate Mixed Hearing Loss', 'Active', NULL, NULL, NULL, NULL),
(64, 1, 'Bilateral Profond SN Hearing Loss', 'Active', NULL, NULL, NULL, NULL),
(65, 1, 'Bil Severe SN Loss', 'Active', NULL, NULL, NULL, NULL),
(66, 1, 'Moderate to serve to hearing loss', 'Active', NULL, NULL, NULL, NULL),
(67, 1, 'Bilatral S N loss', 'Active', NULL, NULL, NULL, NULL),
(68, 1, 'Bilateral Profound SN Hearing impairment', 'Active', NULL, NULL, NULL, NULL),
(69, 1, 'Bil Severe Son Hearing Loss', 'Active', NULL, NULL, NULL, NULL),
(70, 7, 'Both eye Retrobublar neuritis', 'Active', NULL, NULL, NULL, NULL),
(71, 7, 'BE Atypical Reinitis Pigmentosa with Macalopathy', 'Active', NULL, NULL, NULL, NULL),
(72, 7, 'BE Squint with BE Partial optic atrophy with Nystagmus', 'Active', NULL, NULL, NULL, NULL),
(73, 7, 'BE Albinism with Nystagnus', 'Active', NULL, NULL, NULL, NULL),
(74, 7, 'BE Pthisis', 'Active', NULL, NULL, NULL, NULL),
(75, 7, 'BE Pseudophakia with Maculopathy', 'Active', NULL, NULL, NULL, NULL),
(76, 7, 'BE Keratoconus with High Myopia', 'Active', NULL, NULL, NULL, NULL),
(77, 7, 'RE - Pupilary Mem LE - Pthisis Bulbi', 'Active', NULL, NULL, NULL, NULL),
(78, 7, 'Both Eye Pseudophakia with Nystagmus', 'Active', NULL, NULL, NULL, NULL),
(79, 7, 'Right Eye Complicated Cataract Left Eye Uveitis', 'Active', NULL, NULL, NULL, NULL),
(80, 7, 'BE Pseudophakia with Retinopathy', 'Active', NULL, NULL, NULL, NULL),
(81, 7, 'RE Pthisis Bulbi LE Old Uveitis', 'Active', NULL, NULL, NULL, NULL),
(82, 7, 'BE Absolute Glaucomatous Optic', 'Active', NULL, NULL, NULL, NULL),
(83, 7, 'BE Optic Atrophy with Nystagmas', 'Active', NULL, NULL, NULL, NULL),
(84, 7, 'RE Pthisis Bulbi LE Maulopathy', 'Active', NULL, NULL, NULL, NULL),
(85, 7, 'BE Adherent Leucoma', 'Active', NULL, NULL, NULL, NULL),
(86, 7, 'RE Maculopathy LE Pthiasis Bulbi', 'Active', NULL, NULL, NULL, NULL),
(87, 7, 'RE Amblyopla LE Corneal Opacity', 'Active', NULL, NULL, NULL, NULL),
(88, 7, 'Both eye Corneal Degeneration', 'Active', NULL, NULL, NULL, NULL),
(89, 7, 'BE Optic Atrophy', 'Active', NULL, NULL, NULL, NULL),
(90, 7, 'BE Pseudophakia Iridocyclitis', 'Active', NULL, NULL, NULL, NULL),
(91, 7, 'RE Corneal Opacity with LE Central NMO', 'Active', NULL, NULL, NULL, NULL),
(92, 7, 'BE - Pthisis C Nystagmas', 'Active', NULL, NULL, NULL, NULL),
(93, 7, 'RE High Myopla LE Amblyopia', 'Active', NULL, NULL, NULL, NULL),
(94, 7, 'BE Corneal Opacity', 'Active', NULL, NULL, NULL, NULL),
(95, 7, 'RE Adherant Leucoma LE Corneal Degenration', 'Active', NULL, NULL, NULL, NULL),
(96, 7, 'BE Ametropic Ambleopia', 'Active', NULL, NULL, NULL, NULL),
(97, 7, 'RE Retinopathy LE Pthisis Bulbi', 'Active', NULL, NULL, NULL, NULL),
(98, 7, 'BE Pthisis Bulbi', 'Active', NULL, NULL, NULL, NULL),
(99, 7, 'RE Retinal Degenration LE Pthiasis Bulbi', 'Active', NULL, NULL, NULL, NULL),
(100, 7, 'BE Pthiasis Bulbi', 'Active', NULL, NULL, NULL, NULL),
(101, 7, 'Both Eye Vitreous degenration', 'Active', NULL, NULL, NULL, NULL),
(102, 7, 'RE Maculopthy Pterigium', 'Active', NULL, NULL, NULL, NULL),
(103, 7, 'LE Corneal Opacity', 'Active', NULL, NULL, NULL, NULL),
(104, 5, 'Casual Childish, mentally Retardation', 'Active', NULL, NULL, NULL, NULL),
(105, 5, 'Psychosis N. O. S', 'Active', NULL, NULL, NULL, NULL),
(106, 3, 'Knock knee with dwarfism', 'Active', NULL, NULL, NULL, NULL),
(107, 3, 'Pseudo Disability', 'Active', NULL, NULL, NULL, NULL),
(108, 3, 'Synostosis', 'Active', NULL, NULL, NULL, NULL),
(109, 3, 'PPRP Both L/L', 'Active', NULL, NULL, NULL, NULL),
(110, 3, 'Congenital Osteogenesis Imerfecta Both Lower Limbs', 'Active', NULL, NULL, NULL, NULL),
(111, 3, 'Spastic Paresis Both Lower Limbs', 'Active', NULL, NULL, NULL, NULL),
(112, 3, 'RT L/L Shortning', 'Active', NULL, NULL, NULL, NULL),
(113, 3, 'Left Hemiparesis', 'Active', NULL, NULL, NULL, NULL),
(114, 3, 'Bil Perthes disease Hip Both L/L', 'Active', NULL, NULL, NULL, NULL),
(115, 3, 'Spastic Rt/ Upper Limb Rt. UMN Palsy', 'Active', NULL, NULL, NULL, NULL),
(116, 3, 'Bil foot congenital deformity', 'Active', NULL, NULL, NULL, NULL),
(117, 3, 'Congenital Deformity Rt. Foot with Wasting Rt. Leg', 'Active', NULL, NULL, NULL, NULL),
(118, 3, 'Arthrogryposis multiplex congenita', 'Active', NULL, NULL, NULL, NULL),
(119, 3, 'Cerebral Palsy', 'Active', NULL, NULL, NULL, NULL),
(120, 3, 'Left below elbow aplasia', 'Active', NULL, NULL, NULL, NULL),
(121, 3, 'Cerebral Palsy with Spasticity of Both Upper and lower Limb', 'Active', NULL, NULL, NULL, NULL),
(122, 3, 'Bilateral TA contracture', 'Active', NULL, NULL, NULL, NULL),
(123, 3, 'RT Hemiparesis', 'Active', NULL, NULL, NULL, NULL),
(124, 3, 'duchene muscular dystrohy', 'Active', NULL, NULL, NULL, NULL),
(125, 3, 'Spaniel cod injury with pararesis', 'Active', NULL, NULL, NULL, NULL),
(126, 3, 'DMD with Spasticity Both L/L', 'Active', NULL, NULL, NULL, NULL),
(127, 3, 'LT Above knee Amputation', 'Active', NULL, NULL, NULL, NULL),
(128, 3, 'Cerebral Palsy with MR', 'Active', NULL, NULL, NULL, NULL),
(129, 3, 'Bil L/L Deformity', 'Active', NULL, NULL, NULL, NULL),
(130, 3, 'Non Compresive Mylopathy', 'Active', NULL, NULL, NULL, NULL),
(131, 3, 'Traumatic Paraplegia Bilateral lower limbs', 'Active', NULL, NULL, NULL, NULL),
(132, 3, 'CP with Quadriparesis', 'Active', NULL, NULL, NULL, NULL),
(133, 3, 'Traumatic Paraplegia both L/L', 'Active', NULL, NULL, NULL, NULL),
(134, 3, 'CP with Spasticity', 'Active', NULL, NULL, NULL, NULL),
(135, 3, 'DMD', 'Active', NULL, NULL, NULL, NULL),
(136, 3, 'Lt shoulder disarticuetion', 'Active', NULL, NULL, NULL, NULL),
(137, 3, 'Deformity Both Hand and Feet', 'Active', NULL, NULL, NULL, NULL),
(138, 3, 'PPRP RT L/L', 'Active', NULL, NULL, NULL, NULL),
(139, 3, 'Rt. B/K Agenesis', 'Active', NULL, NULL, NULL, NULL),
(140, 3, 'RT Hand Amputation', 'Active', NULL, NULL, NULL, NULL),
(141, 3, 'Congenital pseudoarthrosis of RT Tibia', 'Active', NULL, NULL, NULL, NULL),
(142, 3, 'PPRP Bil L/L', 'Active', NULL, NULL, NULL, NULL),
(143, 3, 'Below Knee LT Traumatic amputation with RT L/L paraparesis both L/L', 'Active', NULL, NULL, NULL, NULL),
(144, 3, 'Weakness Bil L/L', 'Active', NULL, NULL, NULL, NULL),
(145, 3, 'LT BK Amputation', 'Active', NULL, NULL, NULL, NULL),
(146, 3, 'spastic Quadraparesis', 'Active', NULL, NULL, NULL, NULL),
(147, 3, 'C/O Right Lower limb PPRP', 'Active', NULL, NULL, NULL, NULL),
(148, 3, 'Post Traumatic Paraplegia', 'Active', NULL, NULL, NULL, NULL),
(149, 3, 'Lt L/L PPRP', 'Active', NULL, NULL, NULL, NULL),
(150, 3, 'Cerebral palsy', 'Active', NULL, NULL, NULL, NULL),
(151, 3, 'Cp', 'Active', NULL, NULL, NULL, NULL),
(152, 3, 'RT Monoplygia', 'Active', NULL, NULL, NULL, NULL),
(153, 3, 'Post MR Quadriparesis', 'Active', NULL, NULL, NULL, NULL),
(154, 3, 'Spasticity both l/l', 'Active', NULL, NULL, NULL, NULL),
(155, 3, 'Quadriparasis', 'Active', NULL, NULL, NULL, NULL),
(156, 3, 'RT Above Knee Amputation', 'Active', NULL, NULL, NULL, NULL),
(157, 3, 'PPRP Both L/L with severe wasting', 'Active', NULL, NULL, NULL, NULL),
(158, 3, 'CP with Diplegia Bil L/L', 'Active', NULL, NULL, NULL, NULL),
(159, 3, 'Spastic Paraperesis', 'Active', NULL, NULL, NULL, NULL),
(160, 3, 'LT Below Knee Amputation', 'Active', NULL, NULL, NULL, NULL),
(161, 3, 'Both l/l paraparesis', 'Active', NULL, NULL, NULL, NULL),
(162, 3, 'Traumatic Spine Injury with Quadriparesis', 'Active', NULL, NULL, NULL, NULL),
(163, 3, 'Hemophelia with RT Knee FFD and LT Elbow FFD', 'Active', NULL, NULL, NULL, NULL),
(164, 3, 'Congenital Quadriplegia', 'Active', NULL, NULL, NULL, NULL),
(165, 3, 'Bil PPRP L/L', 'Active', NULL, NULL, NULL, NULL),
(166, 3, 'Rt Congenital absence of fore arm', 'Active', NULL, NULL, NULL, NULL),
(167, 3, 'Congenital Deformity Both hands', 'Active', NULL, NULL, NULL, NULL),
(168, 3, 'Profound Intellectual Disability', 'Active', NULL, NULL, NULL, NULL),
(169, 3, 'Kyphoscoliosis D L Spine with deformity with gibbus', 'Active', NULL, NULL, NULL, NULL),
(170, 3, 'LT Hemiparesis', 'Active', NULL, NULL, NULL, NULL),
(171, 3, 'Congenital Dislocation', 'Active', NULL, NULL, NULL, NULL),
(172, 3, 'United RT Ankle', 'Active', NULL, NULL, NULL, NULL),
(173, 3, 'RT Below knee Amputation', 'Active', NULL, NULL, NULL, NULL),
(174, 3, 'RT PPRP L/L', 'Active', NULL, NULL, NULL, NULL),
(175, 3, 'PPRP Both l/l', 'Active', NULL, NULL, NULL, NULL),
(176, 3, 'Post Burn Impairment', 'Active', NULL, NULL, NULL, NULL),
(177, 3, 'PPRP Lt L/L', 'Active', NULL, NULL, NULL, NULL),
(178, 3, 'Above Knee Amputation', 'Active', NULL, NULL, NULL, NULL),
(179, 3, 'Symes Amputation', 'Active', NULL, NULL, NULL, NULL),
(180, 3, 'PPRP Right Lower Limb', 'Active', NULL, NULL, NULL, NULL),
(181, 3, 'Traumatic Below Knee Amputation', 'Active', NULL, NULL, NULL, NULL),
(182, 3, 'Right Above Elbow Amputation', 'Active', NULL, NULL, NULL, NULL),
(183, 3, 'Index Finger Absent', 'Active', NULL, NULL, NULL, NULL),
(184, 3, 'Deforming R Elbow', 'Active', NULL, NULL, NULL, NULL),
(185, 3, 'Spastic Paraplegia', 'Active', NULL, NULL, NULL, NULL),
(186, 3, 'RT U/L VIC', 'Active', NULL, NULL, NULL, NULL),
(187, 3, 'Bil Neglected ctev', 'Active', NULL, NULL, NULL, NULL),
(188, 3, 'Congenital Dislocation of LT hip joint', 'Active', NULL, NULL, NULL, NULL),
(189, 3, 'Lt Club Foot', 'Active', NULL, NULL, NULL, NULL),
(190, 3, 'CP with Diplegia Bil L/L', 'Active', NULL, NULL, NULL, NULL),
(191, 3, 'lt b/k Amputation', 'Active', NULL, NULL, NULL, NULL),
(192, 3, 'Congenital Absence of RT and LT Thumb', 'Active', NULL, NULL, NULL, NULL),
(193, 3, 'LT Thumb Congenital Agenisi, Polyduotyly RT Thumb', 'Active', NULL, NULL, NULL, NULL),
(194, 3, 'Left Hemparesis', 'Active', NULL, NULL, NULL, NULL),
(195, 3, 'Vic LT U/L', 'Active', NULL, NULL, NULL, NULL),
(196, 3, 'rt u/l monoplegia', 'Active', NULL, NULL, NULL, NULL),
(197, 3, 'Muscular Dystrophy both L/L', 'Active', NULL, NULL, NULL, NULL),
(198, 3, 'RT Below Elbow Amputation', 'Active', NULL, NULL, NULL, NULL),
(199, 3, 'Left Elbow Disarticulation', 'Active', NULL, NULL, NULL, NULL),
(200, 3, 'PPRP', 'Active', NULL, NULL, NULL, NULL),
(201, 3, 'lt Monoparesis u/l', 'Active', NULL, NULL, NULL, NULL),
(202, 3, 'RT A K Amputation', 'Active', NULL, NULL, NULL, NULL),
(203, 3, 'Congenital Deformity of Both U/L', 'Active', NULL, NULL, NULL, NULL),
(204, 3, 'Bil CTEV', 'Active', NULL, NULL, NULL, NULL),
(205, 3, 'RT Monoplygiya U/L', 'Active', NULL, NULL, NULL, NULL),
(206, 3, 'LT HemiparIsis', 'Active', NULL, NULL, NULL, NULL),
(207, 3, 'Khyphoscolisis Dorsal Spine', 'Active', NULL, NULL, NULL, NULL),
(208, 3, 'Bilatral CTEV', 'Active', NULL, NULL, NULL, NULL),
(209, 3, 'DMD', 'Active', NULL, NULL, NULL, NULL),
(210, 3, 'Fracture d 12 Parapareisis', 'Active', NULL, NULL, NULL, NULL),
(211, 3, 'rt pprp l/l', 'Active', NULL, NULL, NULL, NULL),
(212, 3, 'Bil Parapareesis l/l', 'Active', NULL, NULL, NULL, NULL),
(213, 3, 'rt b/k Amputation', 'Active', NULL, NULL, NULL, NULL),
(214, 3, 'lt pprp l/l', 'Active', NULL, NULL, NULL, NULL),
(215, 3, 'R/U Synostosis', 'Active', NULL, NULL, NULL, NULL),
(216, 3, 'Post Traumatic Paraparesis', 'Active', NULL, NULL, NULL, NULL),
(217, 3, 'Post Polio Residual Paralysis Right L/L', 'Active', NULL, NULL, NULL, NULL),
(218, 3, 'Post Polio Residual Paralysis', 'Active', NULL, NULL, NULL, NULL),
(219, 3, 'LT Below Elbow Amputation', 'Active', NULL, NULL, NULL, NULL),
(220, 3, 'RT U/L Above Elbow Amputation due to Electric Burn', 'Active', NULL, NULL, 1, '2024-09-19 15:00:51')
ON DUPLICATE KEY UPDATE
  `disability_id` = VALUES(`disability_id`),
  `diagnosis` = VALUES(`diagnosis`),
  `status` = VALUES(`status`),
  `created_by` = VALUES(`created_by`),
  `created_on` = VALUES(`created_on`),
  `updated_by` = VALUES(`updated_by`),
  `updated_on` = VALUES(`updated_on`);

